spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://db_customer:27017/db_customer
server:
  port: 8080
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerType