spring:
  application:
    name: customer-service
  data:
    mongodb:
      database: db_customer
      host: db_customer
      port: 27017
server:
  port: 8080
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerType