eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8889/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-customerProductActives: /api/v1/customerActivesProducts
  path-customerProductPassives: /api/v1/customerPassivesProducts
  path-customerDomain: http://ms-customer:8080
  path-productDomain: http://ms-product:8080
  path-customerResponse: /api/v1/customers/
  path-productResponse: /api/v1/products/
resilience4j:
  circuitbreaker:
    instances:
      ms-customer:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimumNumberOfCalls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:5K8yj70q4RpuiBSE@bootcamp37.anglhbu.mongodb.net/db_customerProduct