eureka:
  client:
    service-url:
      defaultZone: https://ms-discovery.azurewebsites.net/eureka/
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerType
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:5K8yj70q4RpuiBSE@bootcamp37.anglhbu.mongodb.net/db_customer