spring:
  application:
    name: operation-service
  data:
    mongodb:
      database: db_operation
      host: db_operation
      port: 27017
server:
  port: 8083
message:
  path-operation: /api/v1/operations
  path-operationType: /api/v1/operationTypes