spring:
  application:
    name: payment-service
  data:
    mongodb:
      database: db_payment
      host: db_payment
      port: 27017
server:
  port: 8085
message:
  path-payment: /api/v1/payments