spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://db_product:27017/db_product
server:
  port: 8081
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productType