spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://db_product:27017/db_product
server:
  port: 8081
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productType
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8889/eureka/