eureka:
  client:
    service-url:
      defaultZone: https://ms-discovery.azurewebsites.net/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productType
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:5K8yj70q4RpuiBSE@bootcamp37.anglhbu.mongodb.net/db_product