spring:
  application:
    name: shopping-service
  data:
    mongodb:
      database: db_shopping
      host: db_shopping
      port: 27017
server:
  port: 8084
message:
  path-shopping: /api/v1/shoppings